version: '3.8'
services:
  db:
    image: mysql:latest
    platform: windows
    environment:
      MYSQL_DATABASE: hospital_01
      MYSQL_USER: root
      MYSQL_PASSWORD: 0000
    ports:
      - ":3306"
