version: '3.8'
services:
  db:
    image: mysql:latest
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: hospital_01
      MYSQL_USER: user
      MYSQL_PASSWORD: 0000
    ports:
      - ":3306"
