INSERT INTO `doctors` (id, name, birth, sex, address, phone, interests, position, department_id, email)
VALUES (1, 'Yurii Pavlenko', '1981-04-10', 'male', 'Kyiv', NULL, 'Reading, Fencing', 'Engineer', 1,
        'pavlenko.istobud@gmail.com'),
       (2, 'John Smith', '1980-06-15', 'Male', 'Bila Tserkva', NULL, 'Reading, Music, Singing', 'Orthopaedist', 2,
        NULL),
       (3, 'Emily Johnson', '1985-07-22', 'Female', 'Kyiv', NULL, 'Traveling, Cooking, Horses', 'Orthopaedist', 3,
        NULL),
       (4, 'Michael Brown', '1979-04-10', 'Male', 'Kyiv', NULL, 'Photography, Sports', 'Orthopaedist', 4, NULL),
       (5, 'Sophia Martinez', '1982-09-08', 'Female', 'Fastiv', NULL, 'Reading, Gardening', 'Cardiologist', 5, NULL),
       (6, 'David Lee', '1987-02-23', 'Male', 'Chernigiv', NULL, 'Music, Movies, Fencing', 'Cardiologist', 2, NULL),
       (7, 'Olivia Harris', '1990-11-05', 'Female', 'Kyiv', NULL, 'Traveling, Photography', 'Cardiologist', 3, NULL),
       (8, 'James Clark', '1983-03-17', 'Male', 'Kyiv', NULL, 'Sports, Cooking, Hiking', 'Surgeon', 4, NULL),
       (9, 'Ava Lewis', '1978-08-30', 'Female', 'Kyiv', NULL, 'Reading, Music, History', 'Surgeon', 5, NULL),
       (10, 'Daniel Walker', '1985-12-12', 'Male', 'Kyiv', NULL, 'Gardening, Movies', 'Surgeon', 2, NULL),
       (11, 'Mia Robinson', '1992-01-25', 'Female', 'Kyiv', NULL, 'Traveling, Sports', 'Neurologist', 3, NULL),
       (12, 'Ethan Hall', '1984-05-19', 'Male', 'Boyarka', NULL, 'Music, Photography', 'Neurologist', 4, NULL),
       (13, 'Isabella Allen', '1988-10-07', 'Female', 'Gatne', NULL, 'Cooking, Reading, Art', 'Neurologist', 5, NULL);
